### ISSUE TITLE
Runtime Error Warning

### ISSUE THREAD

**Issue by clu5** [zo7/deconvfaces#9]
`MacBook-Pro:deconvfaces-master CJL$ python faces.py train grey_scaled/
Using TensorFlow backend.
Found 0 instances with 0 identities
(5, 4)
height: 5 width: 4
Built model with:
	Deconv layers: 5
	Output shape: (320, 256, 3)
Loading data...
0it [00:00, ?it/s]
Training...
Epoch 1/100
/Users/CJL/anaconda/lib/python3.5/site-packages/keras/callbacks.py:286: RuntimeWarning: Can save best model only with loss available, skipping.
  'skipping.' % (self.monitor), RuntimeWarning)
/Users/CJL/anaconda/lib/python3.5/site-packages/keras/callbacks.py:370: RuntimeWarning: Early stopping requires loss available!
  (self.monitor), RuntimeWarning)
Traceback (most recent call last):
  File "faces.py", line 127, in <module>
    cmd()
  File "faces.py", line 65, in train
    verbose               = True,
  File "/Users/CJL/Downloads/deconvfaces-master/faces/train.py", line 182, in train_model
    callbacks=callbacks, shuffle=True, verbose=1)
  File "/Users/CJL/anaconda/lib/python3.5/site-packages/keras/engine/training.py", line 1124, in fit
    callback_metrics=callback_metrics)
  File "/Users/CJL/anaconda/lib/python3.5/site-packages/keras/engine/training.py", line 862, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/CJL/anaconda/lib/python3.5/site-packages/keras/callbacks.py", line 42, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Users/CJL/anaconda/lib/python3.5/site-packages/keras/callbacks.py", line 372, in on_epoch_end
    if self.monitor_op(current - self.min_delta, self.best):
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'`

I am using a folder of PNG files and getting this error during training. What kinds of image files does it use? How much images did you use to train?

**Comment by flynnmd** [comment]
Hmm that's odd...
1. It says it found 0 instances and 0 identities -- which dataset are you using? This only supports RaFD and Yale Faces (the latter you need to give a flag when you run it, see which with `python3 faces.py train -h`)
2. Which version of Keras are you using? It looks like the model compiled without monitoring the loss (which it should by default), but the callbacks I use to save the model and stop it early need it to work.

**Comment by nmgzjf** [comment]
@clu2033 @zo7 I guess clu2033 use early_stopping in a merge model. It seems that Keras does not provide val_acc and val_loss in merge model, so the monitor only can be set to acc or loss. So if merge model is adopted, please modify the value of monitor.
